<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008071403 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tahun_pelajaran (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tahun VARCHAR(20) NOT NULL, semester VARCHAR(10) NOT NULL, is_active BOOLEAN NOT NULL, tanggal_mulai DATE DEFAULT NULL, tanggal_selesai DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tahun_pelajaran_active ON tahun_pelajaran (is_active)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tahun_semester ON tahun_pelajaran (tahun, semester)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE tahun_pelajaran');
    }
}
