<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008075116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE guru (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nip VARCHAR(30) DEFAULT NULL, nuptk VARCHAR(30) DEFAULT NULL, nik VARCHAR(20) DEFAULT NULL, nama_lengkap VARCHAR(150) NOT NULL, gelar_depan VARCHAR(20) DEFAULT NULL, gelar_belakang VARCHAR(50) DEFAULT NULL, jenis_kelamin VARCHAR(1) NOT NULL, tempat_lahir VARCHAR(100) DEFAULT NULL, tanggal_lahir DATE DEFAULT NULL, agama VARCHAR(30) DEFAULT NULL, alamat TEXT DEFAULT NULL, nomor_hp VARCHAR(20) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, jenis_kepegawaian VARCHAR(30) NOT NULL, status_kepegawaian VARCHAR(20) NOT NULL, pendidikan_terakhir VARCHAR(50) DEFAULT NULL, jurusan_pendidikan VARCHAR(100) DEFAULT NULL, foto_url VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8E924DA59329EEA ON guru (nip)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8E924DA790302ED ON guru (nuptk)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8E924DAD3575706 ON guru (nik)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8E924DAA76ED395 ON guru (user_id)');
        $this->addSql('CREATE INDEX idx_guru_nip ON guru (nip)');
        $this->addSql('CREATE INDEX idx_guru_nuptk ON guru (nuptk)');
        $this->addSql('CREATE INDEX idx_guru_status_pegawai ON guru (status_kepegawaian)');
        $this->addSql('CREATE INDEX idx_guru_jenis_pegawai ON guru (jenis_kepegawaian)');
        $this->addSql('CREATE INDEX idx_guru_is_active ON guru (is_active)');
        $this->addSql('ALTER TABLE guru ADD CONSTRAINT FK_E8E924DAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE guru DROP CONSTRAINT FK_E8E924DAA76ED395');
        $this->addSql('DROP TABLE guru');
    }
}
