<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008083032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mata_pelajaran (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kode_mapel VARCHAR(30) NOT NULL, nama_mapel VARCHAR(150) NOT NULL, kelompok VARCHAR(30) NOT NULL, tingkat INT DEFAULT NULL, jurusan VARCHAR(50) DEFAULT NULL, kkm INT DEFAULT 75 NOT NULL, beban_jam_per_minggu INT DEFAULT 2 NOT NULL, urutan INT DEFAULT 0 NOT NULL, keterangan VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, guru_koordinator_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F16769B1D3E757FE ON mata_pelajaran (kode_mapel)');
        $this->addSql('CREATE INDEX idx_mapel_kode ON mata_pelajaran (kode_mapel)');
        $this->addSql('CREATE INDEX idx_mapel_kelompok ON mata_pelajaran (kelompok)');
        $this->addSql('CREATE INDEX idx_mapel_tingkat ON mata_pelajaran (tingkat)');
        $this->addSql('CREATE INDEX idx_mapel_is_active ON mata_pelajaran (is_active)');
        $this->addSql('CREATE INDEX IDX_F16769B11CEB2414 ON mata_pelajaran (guru_koordinator_id)');
        $this->addSql('CREATE TABLE guru_mata_pelajaran (mata_pelajaran_id BIGINT NOT NULL, guru_id BIGINT NOT NULL, PRIMARY KEY (mata_pelajaran_id, guru_id))');
        $this->addSql('CREATE INDEX IDX_39522AD5C53475F3 ON guru_mata_pelajaran (mata_pelajaran_id)');
        $this->addSql('CREATE INDEX IDX_39522AD5CE61CE44 ON guru_mata_pelajaran (guru_id)');
        $this->addSql('ALTER TABLE mata_pelajaran ADD CONSTRAINT FK_F16769B11CEB2414 FOREIGN KEY (guru_koordinator_id) REFERENCES guru (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE guru_mata_pelajaran ADD CONSTRAINT FK_39522AD5C53475F3 FOREIGN KEY (mata_pelajaran_id) REFERENCES mata_pelajaran (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE guru_mata_pelajaran ADD CONSTRAINT FK_39522AD5CE61CE44 FOREIGN KEY (guru_id) REFERENCES guru (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mata_pelajaran DROP CONSTRAINT FK_F16769B11CEB2414');
        $this->addSql('ALTER TABLE guru_mata_pelajaran DROP CONSTRAINT FK_39522AD5C53475F3');
        $this->addSql('ALTER TABLE guru_mata_pelajaran DROP CONSTRAINT FK_39522AD5CE61CE44');
        $this->addSql('DROP TABLE mata_pelajaran');
        $this->addSql('DROP TABLE guru_mata_pelajaran');
    }
}
