<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008075623 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pegawai (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nip VARCHAR(30) DEFAULT NULL, nuptk VARCHAR(30) DEFAULT NULL, nik VARCHAR(20) DEFAULT NULL, nama_lengkap VARCHAR(150) NOT NULL, gelar_depan VARCHAR(20) DEFAULT NULL, gelar_belakang VARCHAR(50) DEFAULT NULL, jenis_kelamin VARCHAR(1) NOT NULL, tempat_lahir VARCHAR(100) DEFAULT NULL, tanggal_lahir DATE DEFAULT NULL, agama VARCHAR(30) DEFAULT NULL, alamat TEXT DEFAULT NULL, nomor_hp VARCHAR(20) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, kategori_pegawai VARCHAR(30) NOT NULL, jenis_pegawai VARCHAR(30) NOT NULL, status_kepegawaian VARCHAR(20) NOT NULL, jabatan VARCHAR(100) DEFAULT NULL, pendidikan_terakhir VARCHAR(50) DEFAULT NULL, jurusan_pendidikan VARCHAR(100) DEFAULT NULL, tanggal_masuk DATE DEFAULT NULL, foto_url VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9883574859329EEA ON pegawai (nip)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98835748790302ED ON pegawai (nuptk)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98835748D3575706 ON pegawai (nik)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98835748A76ED395 ON pegawai (user_id)');
        $this->addSql('CREATE INDEX idx_pegawai_nip ON pegawai (nip)');
        $this->addSql('CREATE INDEX idx_pegawai_nuptk ON pegawai (nuptk)');
        $this->addSql('CREATE INDEX idx_pegawai_kategori ON pegawai (kategori_pegawai)');
        $this->addSql('CREATE INDEX idx_pegawai_jenis ON pegawai (jenis_pegawai)');
        $this->addSql('CREATE INDEX idx_pegawai_status ON pegawai (status_kepegawaian)');
        $this->addSql('CREATE INDEX idx_pegawai_is_active ON pegawai (is_active)');
        $this->addSql('ALTER TABLE pegawai ADD CONSTRAINT FK_98835748A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE guru DROP CONSTRAINT fk_e8e924daa76ed395');
        $this->addSql('DROP INDEX idx_guru_is_active');
        $this->addSql('DROP INDEX uniq_e8e924da59329eea');
        $this->addSql('DROP INDEX uniq_e8e924da790302ed');
        $this->addSql('DROP INDEX uniq_e8e924dad3575706');
        $this->addSql('DROP INDEX uniq_e8e924daa76ed395');
        $this->addSql('DROP INDEX idx_guru_nip');
        $this->addSql('DROP INDEX idx_guru_nuptk');
        $this->addSql('DROP INDEX idx_guru_status_pegawai');
        $this->addSql('DROP INDEX idx_guru_jenis_pegawai');
        $this->addSql('ALTER TABLE guru ADD bidang_studi_utama VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD is_sertifikasi BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE guru ADD no_sertifikasi VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD tugas_tambahan VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD pegawai_id BIGINT NOT NULL');
        $this->addSql('ALTER TABLE guru DROP nip');
        $this->addSql('ALTER TABLE guru DROP nuptk');
        $this->addSql('ALTER TABLE guru DROP nik');
        $this->addSql('ALTER TABLE guru DROP nama_lengkap');
        $this->addSql('ALTER TABLE guru DROP gelar_depan');
        $this->addSql('ALTER TABLE guru DROP gelar_belakang');
        $this->addSql('ALTER TABLE guru DROP jenis_kelamin');
        $this->addSql('ALTER TABLE guru DROP tempat_lahir');
        $this->addSql('ALTER TABLE guru DROP agama');
        $this->addSql('ALTER TABLE guru DROP alamat');
        $this->addSql('ALTER TABLE guru DROP nomor_hp');
        $this->addSql('ALTER TABLE guru DROP email');
        $this->addSql('ALTER TABLE guru DROP jenis_kepegawaian');
        $this->addSql('ALTER TABLE guru DROP status_kepegawaian');
        $this->addSql('ALTER TABLE guru DROP pendidikan_terakhir');
        $this->addSql('ALTER TABLE guru DROP jurusan_pendidikan');
        $this->addSql('ALTER TABLE guru DROP foto_url');
        $this->addSql('ALTER TABLE guru DROP is_active');
        $this->addSql('ALTER TABLE guru DROP user_id');
        $this->addSql('ALTER TABLE guru RENAME COLUMN tanggal_lahir TO tmt_pendidik');
        $this->addSql('ALTER TABLE guru ADD CONSTRAINT FK_E8E924DA998300D9 FOREIGN KEY (pegawai_id) REFERENCES pegawai (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8E924DA998300D9 ON guru (pegawai_id)');
        $this->addSql('CREATE INDEX idx_guru_pegawai ON guru (pegawai_id)');
        $this->addSql('CREATE INDEX idx_guru_bidang_studi ON guru (bidang_studi_utama)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pegawai DROP CONSTRAINT FK_98835748A76ED395');
        $this->addSql('DROP TABLE pegawai');
        $this->addSql('ALTER TABLE guru DROP CONSTRAINT FK_E8E924DA998300D9');
        $this->addSql('DROP INDEX UNIQ_E8E924DA998300D9');
        $this->addSql('DROP INDEX idx_guru_pegawai');
        $this->addSql('DROP INDEX idx_guru_bidang_studi');
        $this->addSql('ALTER TABLE guru ADD nip VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD nuptk VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD nik VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD nama_lengkap VARCHAR(150) NOT NULL');
        $this->addSql('ALTER TABLE guru ADD gelar_depan VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD jenis_kelamin VARCHAR(1) NOT NULL');
        $this->addSql('ALTER TABLE guru ADD tempat_lahir VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD agama VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD alamat TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD nomor_hp VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD email VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD jenis_kepegawaian VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE guru ADD status_kepegawaian VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE guru ADD pendidikan_terakhir VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD jurusan_pendidikan VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD foto_url VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE guru ADD is_active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE guru ADD user_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE guru DROP bidang_studi_utama');
        $this->addSql('ALTER TABLE guru DROP is_sertifikasi');
        $this->addSql('ALTER TABLE guru DROP tugas_tambahan');
        $this->addSql('ALTER TABLE guru DROP pegawai_id');
        $this->addSql('ALTER TABLE guru RENAME COLUMN no_sertifikasi TO gelar_belakang');
        $this->addSql('ALTER TABLE guru RENAME COLUMN tmt_pendidik TO tanggal_lahir');
        $this->addSql('ALTER TABLE guru ADD CONSTRAINT fk_e8e924daa76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_guru_is_active ON guru (is_active)');
        $this->addSql('CREATE UNIQUE INDEX uniq_e8e924da59329eea ON guru (nip)');
        $this->addSql('CREATE UNIQUE INDEX uniq_e8e924da790302ed ON guru (nuptk)');
        $this->addSql('CREATE UNIQUE INDEX uniq_e8e924dad3575706 ON guru (nik)');
        $this->addSql('CREATE UNIQUE INDEX uniq_e8e924daa76ed395 ON guru (user_id)');
        $this->addSql('CREATE INDEX idx_guru_nip ON guru (nip)');
        $this->addSql('CREATE INDEX idx_guru_nuptk ON guru (nuptk)');
        $this->addSql('CREATE INDEX idx_guru_status_pegawai ON guru (status_kepegawaian)');
        $this->addSql('CREATE INDEX idx_guru_jenis_pegawai ON guru (jenis_kepegawaian)');
    }
}
