<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008073623 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE kelas (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nama_kelas VARCHAR(50) NOT NULL, tingkat INT NOT NULL, jurusan VARCHAR(50) DEFAULT NULL, kapasitas INT DEFAULT 36 NOT NULL, keterangan VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tahun_pelajaran_id SMALLINT DEFAULT NULL, wali_kelas_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_kelas_tingkat ON kelas (tingkat)');
        $this->addSql('CREATE INDEX idx_kelas_tahun_pelajaran ON kelas (tahun_pelajaran_id)');
        $this->addSql('CREATE INDEX idx_kelas_wali ON kelas (wali_kelas_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_kelas_nama_tahun ON kelas (nama_kelas, tahun_pelajaran_id)');
        $this->addSql('ALTER TABLE kelas ADD CONSTRAINT FK_D01FFE54E0C01DC FOREIGN KEY (tahun_pelajaran_id) REFERENCES tahun_pelajaran (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kelas ADD CONSTRAINT FK_D01FFE54CE32E4F8 FOREIGN KEY (wali_kelas_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE kelas DROP CONSTRAINT FK_D01FFE54E0C01DC');
        $this->addSql('ALTER TABLE kelas DROP CONSTRAINT FK_D01FFE54CE32E4F8');
        $this->addSql('DROP TABLE kelas');
    }
}
